# urls for data
BLOCKING_INPUT_DIR = '../blocking_ditto/input_block/'
COYPU_CITIES_PATH = './data/COYPU_start.csv'
SCM_PATH = './data/SCM_start.csv'
COYPU_PATH_PREP = './data/COYPU_prep_data.csv'
SCM_PATH_PREP = './data/SCM_prep_data.csv'

# levenstein comparison threshold 
THRESHOLD = 0.30

# selected countries for comparison
ISO_CODES = ['DE', 'US', 'CN']

REMOVE_COMPANY_SUFFIXES = {
    'DE': {
        'ag', 'se', 'eg', 'ev', 'e v', 'ek', 'e k', 'ohg', 'ug', 'gmbh'
    },
    'INTERNATIONAL': {
        'inc','lc', 'l.c.', 'l.c', 'limited company' ,'limited', 'co'
    } 
}    

REMOVAL_WORDS = ['gmbh', ' co ', 'co.', '&', '.inc', ' inc ', 'inc.', 'llc', 'ltd', 'ltd.', 'kg ',' kg', 'k.g.', ' ag ', 'mbh' , 'gbr', ' ohg ', 'corporation', 'corp', \
    'l.l.c.', ' lp', 'l.p', 'l.p.', ' ag ', 'e v', 'e.V.', ' ev ' ,' ek ', ' ug ', ' eg ', ' pty', 'fpi', '(hk) limited', 'aktiengesellschaft', 'haftungsbeschraenkt', 
    'unternehmergesellschaft', 'kommanditgesellschaft', 'eingetragener verein', 'incorporated', 'gesellschaft mit beschraenkter haftung']

REMOVAL_SEPARATORS = [',', '+', '-', '.', '"']

COMPANY_CATEGORIES = {
    'DE': {
        'gmbh':'co', 'gesellschaft mit beschraenkter haftung': 'co', 'g.m.b.h.' : 'co', 'gmbh & co.' : 'co', 'GmbH und Co.':'co', 'gmbh und co.':'co',
        'kg ':'co', ' kg':'co', 'k.g.':'co' ,'kg' : 'co', 'kommanditgesellschaft':'co',
        ' ag ':'ag', 'aktiengesellschaft': 'ag',
        ' ug': 'co', 'unternehmergesellschaft': 'co', 'haftungsbeschraenkt': 'co',
        ' ohg ': 'co',
        'kirchengemeinden': 'kirche', 'kirche' : 'kirche',
        'erbengemeinschaft': 'erbengemeinschaft',
        'mbh':'co',
        'se':'co',
        'gbr':'gbr',
        'e v':'ev', 'e.V.':'ev', ' ev ': 'ev', 'eingetragener verein': 'ev', ' e V ':'ev', ' ev ':'ev',
        ' ek ':'ek',
        'eingetragene genossenschaft':'eg', ' eg ':'eg',
        'ltd':'co', 'ltd.':'co', 'limited':'co',
        ' co ': 'co', 'co.' : 'co', 'corporation':'co', 'corp': 'co',
        'stiftung': 'stiftung',
        "bank": "bank", 'volksbank':'bank', 'sparkasse': 'bank',
        'gesellschaft zur foerderung': 'co', 'gesellschaft der freunde': 'co',
        'Vermoegensverwaltungsgesellschaft': 'co',
        'gesellschaft buergerlichen rechts mit beschraenkter haftung' : 'gbr mbh',
        'fund': 'fund', 'fonds': 'fonds', 'etf': 'fund', 'fund limited': 'fund', 'trust': 'fund'
        },
    
    'INTERNATIONAL' : {
        ' co ': 'co', 'co.' : 'co', 'corporation':'co', 'corp': 'co',
        '.inc': 'co', ' inc ':'co', 'inc.':'co', 'incorporated': 'co',
        'llc':'co', 'l.l.c.':'co', 'l.c.':'co', 'l.c':'co',
        'lc': 'co', 
        'ltd':'co', 'ltd.':'co', 'limited':'co',
        ' lp':'co', 'l.p.':'co', 'limited partnership': 'co', 'llp': 'co', 'lllp': 'co', 'l.p':'co',
        ' pty':'pty',
        '(hk) limited':'co',
        'fund': 'fund', 'fonds': 'fonds', 'etf': 'fund', 'fund limited': 'fund', 'trust': 'fund',
        'insurance company': 'co', 'travel company': 'co',
        'city of': 'city', 'city': 'city', 'county of':'county', 'county': 'county',
        'church': 'church', 
        'credit union': 'credit union', 'investments': 'investments', 'institute': 'institute','management': 'management', 'advisors': 'advisors', 'trading':'co',
        'investment group' : 'investments'
        },
    'SUFFIX' : {
        'ag':'ag',
        'se':'co', 
        'eg':'eg', 
        'ev':'ev', 
        'e v':'ev',
        'ek': 'ek',
        'ohg':'co',
        'ug':'co',
        'gmbh':'co',
        'inc':'co',
        'lc':'co',
        'l.c.':'co',
        'l.c':'co',
        'limited company':'co',
        'limited':'co',
        'co':'co',
        'inc':'co'
    }    
    }

REMOVAL_WORDS_LOCATION_SCM = [
    " china", 
    "h.k, ",
    "kds, ",
    "china, ",
    "scc, ",
    "japan, ",
    "lux, ",
    "hk, ",
    "foxconn, ",
    " china, s1a s1b s1c",
    ", songjiang",
    "china, ",
    " city",
    ", msc",
    "4403046751, ",
    "sz, ",
    "g.z, ",
    " province",
    " downtown",
    " branch",
    "china, ",
    "szx, ",
    "macao commercial offshore, ",
    "shanghai shenhe thermal magnetic electronics co., ltd., ",
    " ",
    "aoc, ",
    "sip, ",
    "m, ",
    " city",
    "sz, ",
    " china, cfab",
    "prosperity technology, ",
    "group, ",
    "delphi, ",
    "Fujian, ",
    "smic, ",
    " china, united semiconductor",
    " china, fab 16a/b",
    "pumps and industrial fans",
    "asia, ",
    " city",
    "amecco, ",
    " china, ssec",
    "“nexchip”, ",
    "ap, ",
    ", cny invoicing only",
    " bahnhof",
    " germany",
    #"suedwestmetall, ",
    "germany, ",
    #" (, baden",
    "wk plastics, ",
    "formerly poly one corporation, ",
    "europe, ",
    "deutschland",
    #"mitte",
    "deutschland, ",
    "kuenstlersozialkasse, ",
    "international business machines, ",
    #"(, ruhr",
    "pty, ",
    "official, ",
    "fraenkische industrial pipes , ",
    #" (, saar",
    "downers grove, ",
    'suzhou , '
    'germany, ',
    'dongguan, ',
    'import export, ',
    'engineering office, ',
    'm, ',
    'tosoh smd group, ',
    'bp group, ',
    'umc, ',
    'america, ',
    'basf group, ',
    'pty, ',
    'formerly poly one corporation, ',
    'umc, ',
    'uac, ',
    'a division of bachus son , ',
    'manufacturing tooling center, ',
    'ex value plastics, ',
    'former alcoa ees, ',
    'college station',
    'f.s. fehrer automotive, ',
    'americas, ',
    'fpi, ',
    'pidc, ',
    'form. alan l grant centrotrade wurfbain, ',
    'saco community based outpatient clinic',
    'uk, '
]

REMOVAL_WORDS_LOCATION_SCM = [
    " china", 
    "h.k, ",
    "kds, ",
    "china, ",
    "scc, ",
    "japan, ",
    "lux, ",
    "hk, ",
    "foxconn, ",
    " china, s1a s1b s1c",
    "china, ",
    " city",
    ", msc",
    "4403046751, ",
    "sz, ",
    "g.z, ",
    " province",
    " downtown",
    " branch",
    "china, ",
    "szx, ",
    "macao commercial offshore, ",
    "shanghai shenhe thermal magnetic electronics co., ltd., ",
    "aoc, ",
    "sip, ",
    "m, ",
    " city",
    "sz, ",
    " china, cfab",
    "prosperity technology, ",
    "group, ",
    "delphi, ",
    "smic, ",
    " china, united semiconductor",
    " china, fab 16a/b",
    "pumps and industrial fans",
    "asia, ",
    " city",
    "amecco, ",
    " china, ssec",
    "“nexchip”, ",
    "ap, ",
    ", cny invoicing only",
    " bahnhof",
    " germany",
    "suedwestmetall, ",
    "germany, ",
    "wk plastics, ",
    "formerly poly one corporation, ",
    "europe, ",
    "deutschland",
    "deutschland, ",
    "kuenstlersozialkasse, ",
    "international business machines, ",
    "pty, ",
    "official, ",
    "fraenkische industrial pipes , ",
    "downers grove, ",
    'germany, ',
    'import export, ',
    'engineering office, ',
    'm, ',
    'tosoh smd group, ',
    'bp group, ',
    'umc, ',
    'america, ',
    'basf group, ',
    'pty, ',
    'formerly poly one corporation, ',
    'umc, ',
    'uac, ',
    'a division of bachus son , ',
    'manufacturing tooling center, ',
    'ex value plastics, ',
    'former alcoa ees, ',
    'college station',
    'f.s. fehrer automotive, ',
    'americas, ',
    'fpi, ',
    'pidc, ',
    'form. alan l grant centrotrade wurfbain, ',
    'saco community based outpatient clinic',
    'uk, '
]


REMOVAL_WORDS_COMPANY_NAME_SCM = [
    "china", 
    "japan",
    "s1a s1b s1c",
    "songjiang",
    "city",
    "4403046751",
    "province",
    "downtown",
    "branch",
    "Fujian",
    "asia",
    "bahnhof",
    "germany",
    "europe",
    "deutschland",
    "mitte",
    'suzhou'
    'dongguan',
    'america',
    'americas',
    'uk'
]
